"""Initial migration

Revision ID: 9e2eba505de8
Revises: 
Create Date: 2022-04-14 04:57:03.950592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2eba505de8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('month_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('income', sa.Float(), nullable=True),
    sa.Column('money_for_month', sa.Float(), nullable=True),
    sa.Column('money_for_day', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('name_of_item', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('quantity_type', sa.String(length=5), nullable=True),
    sa.Column('spending_amount', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types_of_month_spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_type', sa.String(length=40), nullable=True),
    sa.Column('amount_in_percent', sa.Float(), nullable=True),
    sa.Column('amount_in_money', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_everyday', sa.Boolean(), nullable=True),
    sa.Column('month_plan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['month_plan'], ['month_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types_of_month_spend')
    op.drop_table('spendings')
    op.drop_table('month_plans')
    op.drop_table('users')
    # ### end Alembic commands ###
